### ISSUE TITLE
no match for platform in manifest 

### ISSUE THREAD

**Issue by joepio** [Docker-Hub-frolvlad/docker-alpine-glibc#62] opened 2023-01-26 11:15 UTC
Hi there! I've got a dockerfile using `frovlad/alpine-glibc` [in a project](https://github.com/atomicdata-dev/atomic-data-rust/issues/568) which seems to have broken the build for my usecase since yesterday.

```
frolvlad/alpine-glibc: no match for platform in manifest sha256:44a54734fa33b549162845a9839fa4c745c5132a1e59f5d871c681050a9dd6bb: not found
```

Not sure what this means, but I assume it has something to do with the build from yesterday. If I switch back to `frolvlad/alpine-glibc:alpine-3.16_glibc-2.34` everything works.

**Comment by frol** [comment] 2023-01-27 10:23
@joepio I feel there were some changes on Docker Hub or even on the Docker side, but when I explicitly specify the platform, it works fine even on my macOS ARM64:

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/304265/215063586-cd83dd6f-3026-4339-be1a-2db548fd2082.png">

**Comment by joepio** [comment] 2023-01-27 11:19
Adding `--platform linux/amd64` helps when manually pulling, indeed.

But when pulling without that flag on my m1 mac `latest` fails, the previous version works fine:

```
docker pull frolvlad/alpine-glibc:latest
4a62babbd89d: Download complete
no match for platform in manifest: not found
```

```
docker pull frolvlad/alpine-glibc:alpine-3.16_glibc-2.34
a3e7c6fa4bc1: Exists
89eb7d1be3de: Exists
docker.io/frolvlad/alpine-glibc:alpine-3.16_glibc-2.34
```

**Comment by frol** [comment] 2023-01-27 12:12
@joepio There were no changes in the image itself, so there is nothing I can fix here. The image is only available for linux/amd64, and it works. I'll close this issue because there's no action item here. I would love to hear if anyone would uncover the root cause and I am happy to apply any changes to CI or Dockerfile if PR is submitted.

**Closed by frol** 2023-01-27 12:12 UTC
